### PR TITLE
Feat/gemspec

### PR DESCRIPTION
**Pull request by ctlong**
- Fixed certain gemspec aspects that were hooked into exe (we use bin)
- Updated description
- Added a post install message :smiling_imp:

### CODE REVIEW

**Comment by ctlong** [comment]
@wingleungchoi Do you want to keep the two structure PRs we created a while back for any reason or can I delete them?

**Comment by ctlong** [comment]
@wingleungchoi Once this is merged I will try and publish gem using `rake build` and `rake release`. If you send me your email for a RubyGems account you control I can also [add you as an owner](http://guides.rubygems.org/command-reference/#gem-owner).

**Comment by wingleungchoi** [comment]
@ctlong  👏 
Yes, please delete those two PR.
I have not create RubyGems yet. Will let you know when i create.

**Comment by wingleungchoi** [comment]
@ctlong  my RubyGems email is wingleungchoi@gmail.com

**Comment by ctlong** [comment]
@wingleungchoi Done the gem is (live on rubygems)[https://rubygems.org/gems/address_geocoder] and I've added you as an owner for pushing releases.

**Pull request merged**
